# Generated by Django 3.2.6 on 2022-08-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('token', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Token Приложения')),
            ],
            options={
                'db_table': 'apps',
                'managed': True,
            },
        ),
    ]
