# Generated by Django 3.2.6 on 2022-08-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default='История Кочки', max_length=100, verbose_name='Название'),
        ),
    ]
